# Generated by Django 4.2 on 2023-04-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainTatarin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="sublevel",
            field=models.IntegerField(default=1, verbose_name="Уровень сложности"),
        ),
    ]
