# Generated by Django 4.2 on 2023-04-26 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainTatarin", "0002_level_sublevel"),
    ]

    operations = [
        migrations.AddField(
            model_name="theory",
            name="bonus",
            field=models.BooleanField(default=False, verbose_name="Бонусная теория"),
        ),
        migrations.AlterField(
            model_name="level",
            name="answer",
            field=models.CharField(max_length=64, verbose_name="Ответ на вопрос"),
        ),
        migrations.AlterField(
            model_name="level",
            name="task",
            field=models.TextField(verbose_name="Вопрос для пользователя"),
        ),
        migrations.AlterField(
            model_name="reward",
            name="hash",
            field=models.CharField(max_length=46, verbose_name="Хэш NFT в IPFS"),
        ),
        migrations.AlterField(
            model_name="reward",
            name="theory",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="TheoryOf",
                to="mainTatarin.theory",
            ),
        ),
        migrations.AlterField(
            model_name="theory",
            name="content",
            field=models.TextField(verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="theory",
            name="topic",
            field=models.CharField(max_length=32, verbose_name="Тема"),
        ),
    ]
