# Generated by Django 3.2.16 on 2023-04-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainTatarin', '0003_theory_bonus_alter_level_answer_alter_level_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Номер уровня в зависимости от сложности'),
        ),
    ]
