# Generated by Django 4.2 on 2023-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mainTatarin",
            "0003_theory_bonus_alter_level_answer_alter_level_task_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="number",
            field=models.IntegerField(
                default=1, verbose_name="Номер уровня в зависимости от сложности"
            ),
        ),
    ]
